[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    # "-C", "linker=riscv64-unknown-elf-gcc",
    # "-C", "link-arg=-mcmodel=medany",
    "-C",
    "code-model=medium",
    "-C",
    "link-arg=-Tlinker.ld",
    # "-C", "relocation-model=static",
]
